// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_tpqhqnik2-6ynuNCWbgh2n9zDIvyIA',
    appId: '1:152293857166:web:6a8633e5b476f081a8b6df',
    messagingSenderId: '152293857166',
    projectId: 'twitter-30fa8',
    authDomain: 'twitter-30fa8.firebaseapp.com',
    storageBucket: 'twitter-30fa8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7oyDwlfjSwxt9br1YEEG4KmlQnOFaRxo',
    appId: '1:152293857166:android:40740026bf1fafa3a8b6df',
    messagingSenderId: '152293857166',
    projectId: 'twitter-30fa8',
    storageBucket: 'twitter-30fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM5_9dvNvfu9A3j-axMSmi67z5EfvDLTY',
    appId: '1:152293857166:ios:b837c4c7c2438c92a8b6df',
    messagingSenderId: '152293857166',
    projectId: 'twitter-30fa8',
    storageBucket: 'twitter-30fa8.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM5_9dvNvfu9A3j-axMSmi67z5EfvDLTY',
    appId: '1:152293857166:ios:b837c4c7c2438c92a8b6df',
    messagingSenderId: '152293857166',
    projectId: 'twitter-30fa8',
    storageBucket: 'twitter-30fa8.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0_tpqhqnik2-6ynuNCWbgh2n9zDIvyIA',
    appId: '1:152293857166:web:86c55b474b5fb28da8b6df',
    messagingSenderId: '152293857166',
    projectId: 'twitter-30fa8',
    authDomain: 'twitter-30fa8.firebaseapp.com',
    storageBucket: 'twitter-30fa8.appspot.com',
  );
}
